package(default_visibility = ["//visibility:public"])

cc_library(
    name = "fmt_eigen",
    hdrs = ["fmt_eigen.h"],
    deps = [
      "@eigen",
      "@fmt",
    ]
)

cc_library(
    name = "singleton",
    hdrs = ["singleton.h"],
    deps = [
      "//uom/common:defines",
    ],
)
